r"""Keeps the engineering-log index true, and regenerates it.

WHY THIS EXISTS:
The log is ~105 entries and was a single 589 KB file — the project's most
valuable artifact, and effectively unnavigable: no table of contents, no
anchors, and three incompatible entry formats accreted over 88 milestones.
It is now `docs/MILESTONES.md` (a ~21 KB index) plus `docs/milestones/part-N.md`.

That shape only stays useful if the index stays true, and a hand-maintained
index over a log that gains entries is a doc-drift bug waiting to happen. This
project already had one of those (see tests/env_docs_test.py). So the index
is GENERATED, and this file is both the generator and the gate:

    python scripts\milestones_toc_test.py            # CHECK  (exit 1 on drift)
    python scripts\milestones_toc_test.py --write    # regenerate in place

Two things are checked, and the second is the one that matters most:

  1. the generated index block matches the entries actually in the parts, and
  2. EVERY internal link in MILESTONES.md resolves — the target file exists and
     contains a heading with that anchor.

(2) covers the hand-written "Start here" table, whose links point across files
and would otherwise rot silently the first time an entry is renamed or moves
between parts. A dead link in the one section a reader is steered to first is
worse than no section at all.

Anchors follow GitHub's slug rules: lowercase, drop anything that is not a
letter/digit/space/hyphen, spaces to hyphens, numeric suffix on collisions.
Em-dashes vanish, which is why anchors carry a double hyphen — correct, not a bug.
"""

from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "MILESTONES.md"
PARTS_DIR = ROOT / "docs" / "milestones"

BEGIN = "<!-- INDEX:BEGIN — generated by tests/milestones_toc_test.py; do not edit by hand -->"
END = "<!-- INDEX:END -->"

WRITE = "--write" in sys.argv
DATE = re.compile(r"(20\d\d-\d\d-\d\d)")
LINK = re.compile(r"\]\(([^)]+)\)")


def slug(heading: str) -> str:
    s = unicodedata.normalize("NFKC", heading).lower()
    s = "".join(c for c in s if c.isalnum() or c in " -_")
    return s.replace(" ", "-")


def part_files() -> list[Path]:
    return sorted(PARTS_DIR.glob("part-*.md"),
                  key=lambda p: int(re.search(r"\d+", p.stem).group()))


def anchors_of(path: Path) -> set[str]:
    """Every heading anchor GitHub would generate for this file."""
    seen: dict[str, int] = {}
    out: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("#"):
            continue
        title = line.lstrip("#").strip()
        a = slug(title)
        n = seen.get(a, 0)
        seen[a] = n + 1
        out.add(a if not n else f"{a}-{n}")
    return out


def build_index() -> str:
    blocks: list[str] = []
    for path in part_files():
        text = path.read_text(encoding="utf-8")
        titles = [ln[3:].strip() for ln in text.splitlines() if ln.startswith("## ")]
        dates = sorted(set(DATE.findall(text)))
        rng = "" if not dates else (
            dates[0] if dates[0] == dates[-1] else f"{dates[0]} to {dates[-1]}"
        )
        label = f"Part {re.search(r'\d+', path.stem).group()}"
        if rng:
            label += f" — {rng}"
        seen: dict[str, int] = {}
        rows = []
        for t in titles:
            a = slug(t)
            n = seen.get(a, 0)
            seen[a] = n + 1
            if n:
                a = f"{a}-{n}"
            rows.append(f"- [{t}](milestones/{path.name}#{a})")
        blocks.append(
            f"<details>\n"
            f"<summary><strong>{label} ({len(titles)} entries)</strong></summary>\n\n"
            + "\n".join(rows)
            + "\n\n</details>\n"
        )
    return BEGIN + "\n\n" + "\n".join(blocks) + "\n" + END


def main() -> int:
    text = DOC.read_text(encoding="utf-8")
    index = build_index()

    if BEGIN in text and END in text:
        start, stop = text.index(BEGIN), text.index(END) + len(END)
        current = text[start:stop]
        new_text = text[:start] + index + text[stop:]
    else:
        current, new_text = None, text

    if WRITE:
        if current is None:
            print("  no INDEX:BEGIN/END markers in MILESTONES.md", file=sys.stderr)
            return 1
        DOC.write_text(new_text, encoding="utf-8")
        print(f"  wrote index ({index.count(chr(10) + '- [')} entries)")
        return 0

    passed = failed = 0

    def check(label: str, ok: bool, detail: str = "") -> None:
        nonlocal passed, failed
        if ok:
            passed += 1
            print(f"  PASS  {label}")
        else:
            failed += 1
            print(f"  FAIL  {label}")
            if detail:
                for ln in detail.splitlines():
                    print(f"          {ln}")

    check("MILESTONES.md has a generated index block", current is not None,
          "run:  python tests/milestones_toc_test.py --write")
    check("log is split into part files", len(part_files()) > 0,
          "expected docs/milestones/part-*.md")

    if current is not None:
        check("index matches the entries in the part files", current == index,
              "an entry was added, renamed, or moved between parts.\n"
              "run:  python tests/milestones_toc_test.py --write")

    # --- the load-bearing check: every internal link resolves --------------
    anchor_cache: dict[Path, set[str]] = {}
    broken: list[str] = []
    for target in LINK.findall(text):
        if target.startswith(("http://", "https://", "mailto:")):
            continue
        path_part, _, anchor = target.partition("#")
        dest = DOC.parent / path_part if path_part else DOC
        if not dest.exists():
            broken.append(f"{target}  (no such file)")
            continue
        if anchor:
            if dest not in anchor_cache:
                anchor_cache[dest] = anchors_of(dest)
            if anchor not in anchor_cache[dest]:
                broken.append(f"{target}  (no heading with that anchor)")

    check(
        "every internal link in MILESTONES.md resolves",
        not broken,
        "\n".join(broken[:12]) + (f"\n... and {len(broken)-12} more" if len(broken) > 12 else ""),
    )

    total = sum(
        len([1 for ln in p.read_text(encoding="utf-8").splitlines() if ln.startswith("## ")])
        for p in part_files()
    )
    check("the log still holds its entries", total >= 100,
          f"found {total} — expected ~105")

    print(f"\n{passed} passed, {failed} failed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
