r"""Re-test whether web_search_20260209 still breaks the agentic loop.

BACKGROUND (2026-06-02, commit 02e5b91):
`WEB_SEARCH_TOOL` was pinned back to the GA `web_search_20250305` after live
400s. The newer `_20260209` adds dynamic filtering, which runs an Anthropic-side
code-execution container; the API then requires that container's id to be echoed
on every subsequent request in the same exchange. Interleaving a server-side
search with a CLIENT-side tool call (several web_searches + set_reminders in one
turn) produced:

    400 "container_id is required when there are pending tool uses
         generated by code execution with tools."

The recorded reasoning was that the loop "can't reliably thread" that id, and
that downgrading removes the container — and therefore the error class —
entirely. Container-capture was kept as defense-in-depth.

WHY RE-TEST:
That assumption is now the only thing holding the pin, and it is testable. The
loop DOES capture the container and thread it (`stream_kwargs["container"]`).
Dynamic filtering filters search results server-side before they enter the
context window, which on a tool-heavy assistant is a real token saving — the
2026-06-02 note called the benefit "marginal for voice queries", which was a
judgement made while the feature was broken, not a measurement of it working.

So: drive the REAL agentic loop with queries deliberately shaped to interleave
a server-side search with a client-side tool — the exact failure shape — under
both tool versions, and count 400s.

An instrument, not a gate: live API calls, no network in CI. Deliberately NOT
named `*_test.py`.

    venv\Scripts\python.exe scripts\web_search_version_probe.py

NOTE: every query below uses READ-ONLY client tools. The original repro used
set_reminder, which would write to reminders.json — a probe must not mutate
real state to reproduce a routing bug.
"""

from __future__ import annotations

import argparse
import statistics
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src import llm  # noqa: E402
from src.config import load  # noqa: E402

VERSIONS = {
    "20250305 (pinned)": ("web_search_20250305", "web_fetch_20250910"),
    "20260209 (dynamic)": ("web_search_20260209", "web_fetch_20260209"),
}

# Shaped to force server-search -> client-tool interleaving inside ONE turn,
# which is what produced the 400. Read-only client tools only.
QUERIES = [
    "Search the web for the latest news on AI regulation, then tell me the "
    "weather in Austin, Texas.",

    "Look up online who won the last two Super Bowls, and also check how much "
    "RAM this machine is using right now.",

    "Search the web for reviews of the Framework laptop, then find out how "
    "long Baldur's Gate 3 takes to beat.",

    "Search the web for three things: the current weather in Tokyo, the latest "
    "SpaceX launch, and who directed Oppenheimer. Then check this PC's disk space.",
]


def run(api_key: str, question: str) -> dict:
    box: dict = {}
    t0 = time.monotonic()
    try:
        for _ in llm.stream_response(
            api_key=api_key,
            messages=[{"role": "user", "content": question}],
            model="claude-sonnet-5",
            on_complete=lambda rec: box.update(rec=rec),
        ):
            pass
    except Exception as exc:
        msg = str(exc)
        return {
            "ok": False,
            "container_400": "container_id" in msg,
            "err": f"{type(exc).__name__}: {msg}"[:200],
            "elapsed": time.monotonic() - t0,
        }
    rec = box.get("rec")
    return {
        "ok": True,
        "container_400": False,
        "elapsed": rec.elapsed_sec if rec else time.monotonic() - t0,
        "in_tok": rec.input_tokens if rec else 0,
        "out_tok": rec.output_tokens if rec else 0,
        "cache_read": rec.cache_read_tokens if rec else 0,
        "iters": rec.iterations if rec else 0,
        "tools": list(rec.tools_used) if rec else [],
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repeat", type=int, default=2)
    args = ap.parse_args()

    cfg = load()
    if not cfg.anthropic_api_key:
        print("ANTHROPIC_API_KEY not set", file=sys.stderr)
        return 1

    orig_search = dict(llm.WEB_SEARCH_TOOL)
    orig_fetch = dict(llm.WEB_FETCH_TOOL)
    results: dict[str, list[dict]] = {}

    try:
        # Interleave versions per query so API load drift hits both equally —
        # the ordering lesson from the effort probe (M89).
        for qi, q in enumerate(QUERIES):
            print(f"\n=== {q[:88]}")
            for rep in range(args.repeat):
                names = list(VERSIONS)
                if (qi + rep) % 2:
                    names.reverse()
                for label in names:
                    s_type, f_type = VERSIONS[label]
                    llm.WEB_SEARCH_TOOL["type"] = s_type
                    llm.WEB_FETCH_TOOL["type"] = f_type
                    r = run(cfg.anthropic_api_key, q)
                    results.setdefault(label, []).append(r)
                    if r["ok"]:
                        print(f"  OK   {label:20s} {r['elapsed']:5.1f}s  "
                              f"in={r['in_tok']:5d} out={r['out_tok']:4d} "
                              f"cache_read={r['cache_read']:6d} iters={r['iters']} "
                              f"tools={','.join(r['tools']) or '(none)'}")
                    else:
                        tag = "CONTAINER_400" if r["container_400"] else "ERROR"
                        print(f"  {tag:13s} {label:20s} {r['err']}")
    finally:
        llm.WEB_SEARCH_TOOL.clear(); llm.WEB_SEARCH_TOOL.update(orig_search)
        llm.WEB_FETCH_TOOL.clear(); llm.WEB_FETCH_TOOL.update(orig_fetch)

    print("\n" + "=" * 78)
    print(f"{'version':22s} {'ok':>6s} {'400s':>6s} {'med lat':>8s} "
          f"{'in tok':>8s} {'out tok':>8s}")
    print("-" * 78)
    for label, rs in results.items():
        ok = [r for r in rs if r["ok"]]
        n400 = sum(1 for r in rs if r["container_400"])
        lat = f"{statistics.median(r['elapsed'] for r in ok):7.1f}s" if ok else "      -"
        itok = f"{statistics.mean(r['in_tok'] for r in ok):8.0f}" if ok else "       -"
        otok = f"{statistics.mean(r['out_tok'] for r in ok):8.0f}" if ok else "       -"
        print(f"{label:22s} {len(ok):3d}/{len(rs):<2d} {n400:>6d} {lat} {itok} {otok}")
    print("=" * 78)
    print("A single container_id 400 keeps the pin. The token columns only\n"
          "matter if the 400 column is zero.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
